# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 831, 511))
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #0f3008;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(290, 360, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-radius: 7px;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(560, 410, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:#ffb96e;\n"
"    border-radius: 7px;\n"
"    background-color: #08632b;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #074d22;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #06401c;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/settings/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 410, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: #08632b;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:#074d22;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #06401c;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/settings/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 460, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:#bdffdc;\n"
"    border-radius: 7px;\n"
"    background-color: #08632b;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #074d22;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#06401c;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/settings/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 271, 491))
        self.frame_4.setStyleSheet("QFrame{\n"
"    color: white;\n"
"    border-radius: 7px;\n"
"    background-color: #1d5e0e;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 130, 71, 71))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_010.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 130, 71, 71))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"")
        self.pushButton_8.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_011.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon4)
        self.pushButton_8.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 130, 71, 71))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_9.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_013.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 50, 71, 71))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"")
        self.pushButton_10.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_002.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon6)
        self.pushButton_10.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 50, 71, 71))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_11.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_005.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon7)
        self.pushButton_11.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 50, 71, 71))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_12.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_006.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon8)
        self.pushButton_12.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 210, 71, 71))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_13.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_026 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon9)
        self.pushButton_13.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 290, 71, 71))
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_14.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_048.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon10)
        self.pushButton_14.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_15.setGeometry(QtCore.QRect(100, 290, 71, 71))
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_15.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_001.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon11)
        self.pushButton_15.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_16.setGeometry(QtCore.QRect(190, 210, 71, 71))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_16.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_044.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon12)
        self.pushButton_16.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_17.setGeometry(QtCore.QRect(100, 210, 71, 71))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_17.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_033.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon13)
        self.pushButton_17.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_18.setGeometry(QtCore.QRect(190, 290, 71, 71))
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_18.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_007.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon14)
        self.pushButton_18.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 370, 71, 71))
        self.pushButton_21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_21.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_015.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_21.setIcon(icon15)
        self.pushButton_21.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_22.setGeometry(QtCore.QRect(100, 370, 71, 71))
        self.pushButton_22.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"")
        self.pushButton_22.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_018.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_22.setIcon(icon16)
        self.pushButton_22.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_24.setGeometry(QtCore.QRect(190, 370, 71, 71))
        self.pushButton_24.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    color:#c4c5ff;\n"
"    border-radius: 7px;\n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(85, 255, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(57, 172, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_24.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("icons/emoji/lunaVK_014.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_24.setIcon(icon17)
        self.pushButton_24.setIconSize(QtCore.QSize(64, 64))
        self.pushButton_24.setObjectName("pushButton_24")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(0, 0, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#ecff6e;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 460, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color:#ffd09e;\n"
"    border-radius: 7px;\n"
"    background-color: #08632b;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #074d22\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #06401c;\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("icons/settings/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon18)
        self.pushButton_7.setObjectName("pushButton_7")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(290, 10, 531, 341))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setTabletTracking(False)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setStyleSheet("color: white;\n"
"border-radius: 7px;\n"
"background-color: #1d5e0e;\n"
"")
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidget.setLineWidth(1)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setAutoScroll(True)
        self.listWidget.setTabKeyNavigation(False)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setDragDropOverwriteMode(False)
        self.listWidget.setAlternatingRowColors(False)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.listWidget.setMovement(QtWidgets.QListView.Static)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setWordWrap(False)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Сообщение"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.pushButton_2.setText(_translate("MainWindow", "Подключиться к серверу"))
        self.pushButton_4.setText(_translate("MainWindow", "Очистить "))
        self.label.setText(_translate("MainWindow", "Emoji"))
        self.pushButton_7.setText(_translate("MainWindow", "Настройки подключения"))
        self.listWidget.setSortingEnabled(False)
